batch_size: 256
optimizer: adam
learning_rate: 0.005
start_lr: 0.00001
final_lr: 0.000001
warmup_epochs: 4
max_epoch: 50
patience: 3
weight_decay: 0.000001
lars_wrapper: False
architecture: kpts_regressor
backbone: resnet50
first_conv: True
maxpool1: True
dropout: 0
use_final_pool: True
exclude_bn_bias: False
input_height: 224
tuple_length: 1
frame_offset: 1
tuple_offset: 1
exp_name: baseline_sortedkpts
gpus: 1
num_workers: 4
seed: None
precision: 16
early_stop_metric: val_loss
log_proj_errors: False
gaussian_blur: True
jitter_strength: 1.0
shared_transform: True
crop_height: "auto"
crop_scale_min: 0.8
crop_scale_max: 1.0
crop_ratio_min: 0.75
crop_ratio_max: 1.33
crop_strategy: centroid
sync_hflip: False
keep_only_frames_with_valid_kpts: True
use_hflip_augment: False
resort_keypoints: True
